### ISSUE TITLE
deadlock in get_reindexed api

### ISSUE THREAD

**Issue by westfly** [hosseinmoein/DataFrame#132]
I review the code 

```cpp

template<typename I, typename  H>
template<typename T, typename ... Ts>
StdDataFrame<T> DataFrame<I, H>::
get_reindexed(const char *col_to_be_index, const char *old_index_name) const  {
  ...
     for (auto citer : column_list_)  {
        if (citer.first == col_to_be_index)  continue;

        load_functor_<StdDataFrame<T>, Ts ...>  functor (
            citer.first.c_str(),
            0,
            new_idx_s,
            result,
            nan_policy::dont_pad_with_nans);
        const SpinGuard                         guard(lock_);

        data_[citer.second].change(functor);
    }
   ...
}
```
It's same  that inside load_functor_ has lock guard?

thread_stack 
```thread_stack
Thread 2 (Thread 0x7fb0a9a13700 (LWP 22679)):
#0  lock (this=<optimized out>) at /data/DataFrame/include/DataFrame/Utils/ThreadGranularity.h:97
#1  SpinGuard (l=0xdb75bc <ranker::InitDataFrameLock()::hmdf_lock>, this=<synthetic pointer>) at /data/DataFrame/include/DataFrame/Utils/ThreadGranularity.h:117
#2  hmdf::DataFrame<unsigned long, hmdf::HeteroVector>::create_column<long> (this=this@entry=0x7fb0a9a10800, name=<optimized out>, name@entry=0x7fb0a9a107b8 "time") at /data/DataFrame/include/DataFrame/Internals/DataFrame_set.tcc:52
#3  0x000000000047e2ef in hmdf::DataFrame<unsigned long, hmdf::HeteroVector>::load_column<long>(char const*, std::vector<long, std::allocator<long> >&&, hmdf::nan_policy) (this=this@entry=0x7fb0a9a10800, name=name@entry=0x7fb0a9a107b8 "time", column=column@entry=<unknown type in /home/aresyang/vista/ranker_env/ranker/build/data_frame_bench, CU 0x2d6efa, DIE 0x4c6abb>, padding=padding@entry=hmdf::dont_pad_with_nans) at /data/DataFrame/include/DataFrame/Internals/DataFrame_set.tcc:452
#4  0x000000000048047b in operator()<std::vector<long int> > (vec=..., this=<synthetic pointer>) at /data/DataFrame/include/DataFrame/Internals/DataFrame_misc.tcc:98
#5  change_impl_help_<hmdf::DataFrame<unsigned long, hmdf::HeteroVector>::load_functor_<hmdf::DataFrame<unsigned long, hmdf::HeteroVector>, std::basic_string_view<char, std::char_traits<char> >, unsigned long, long, hmdf::DateTime>&, long> (functor=<synthetic pointer>, this=0x4e7acd50700) at /data/DataFrame/include/DataFrame/Vectors/HeteroVector.tcc:173
#6  change_impl_<hmdf::DataFrame<unsigned long, hmdf::HeteroVector>::load_functor_<hmdf::DataFrame<unsigned long, hmdf::HeteroVector>, std::basic_string_view<char, std::char_traits<char> >, unsigned long, long, hmdf::DateTime>&, hmdf::HeteroVector::type_list, std::basic_string_view<char, std::char_traits<char> >, unsigned long, long, hmdf::DateTime> (functor=<synthetic pointer>, this=0x4e7acd50700) at /data/DataFrame/include/DataFrame/Vectors/HeteroVector.tcc:220
#7  change<hmdf::DataFrame<unsigned long, hmdf::HeteroVector>::load_functor_<hmdf::DataFrame<unsigned long, hmdf::HeteroVector>, std::basic_string_view<char, std::char_traits<char> >, unsigned long, long, hmdf::DateTime>&> (functor=<synthetic pointer>, this=<optimized out>) at /data/DataFrame/include/DataFrame/Vectors/HeteroVector.h:192
#8  hmdf::DataFrame<unsigned long, hmdf::HeteroVector>::get_reindexed<unsigned long, std::basic_string_view<char, std::char_traits<char> >, unsigned long, long, hmdf::DateTime> (this=this@entry=0x7fb0a9a10c70, col_to_be_index=col_to_be_index@entry=0x9cd746 "NEW_IDX", old_index_name=old_index_name@entry=0x9cd74e "OLD_IDX") at /data/DataFrame/include/DataFrame/Internals/DataFrame_get.tcc:1083
```

**Comment by hosseinmoein** [comment]
Thanks, will look and fix over the weekend

**Comment by hosseinmoein** [comment]
@westfly , this has been fixed in master. Please check it out

**Comment by westfly** [comment]
> @westfly , this has been fixed in master. Please check it out

@hosseinmoein thx for your great work.
